# Добавим ключ репозитория для последующей работы с ним
- name: Add APT key
  tags: install
  apt_key:
    id: EA312927
    keyserver: keyserver.ubuntu.com

# Подключаем репозиторий с пакетами mongodb
- name: Add APT repository
  tags: install
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present

# Выполним установку пакета
- name: Install mongodb package
  tags: install
  apt:
    name: mongodb-org
    state: present

- name: Configure service supervisor
  tags: install
  systemd:
    name: mongod
    enabled: yes
    state: started