---
# tasks file for db

- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Change MongoDB config file
  notify: restart mongod
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    mode: 0644