---
- name: Configure MongoDB
  hosts: db
  become: true

  vars:
    mongo_bind_ip: 0.0.0.0

  tasks:
    - name: Change MongoDB config file
      notify: restart mongod
      template:
        src: ../templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644

  handlers:
    - name: restart mongod
      service: name=mongod state=restarted