---
- name: Configure hosts & deploy application
  hosts: all
  tasks:
    - name: Change MongoDB config file
      become: true
      tags: db-tag
      template:
        src: ../templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644