---
- name: Configure hosts & deploy application
  hosts: all

  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 10.132.0.2

  tasks:
    - name: Change MongoDB config file
      become: true
      tags: db-tag
      notify: restart mongod
      template:
        src: ../templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644

    - name: Add config for MongoDB connection
      tags: app-tag
      template:
        src: ../templates/db_config.j2
        dest: /home/appuser/db_config

    - name: Add unit file for Puma
      become: true
      tags: app-tag
      notify: reload puma
      copy:
        src: ../files/puma.service
        dest: /etc/systemd/system/puma.service

    - name: Enable Puma
      become: true
      tags: app-tag
      systemd: name=puma enabled=true

  handlers:
    - name: restart mongod
      become: true
      service: name=mongod state=restarted

    - name: reload puma
      become: true
      service: name=puma state=reloaded