---
- name: Install ruby and rubygems and required packages
  tags: ruby
  apt: "name={{ item }} state=present"
  with_items:
    - ruby-full
    - ruby-dev
    - build-essential

- name: Install Ruby bundler
  tags: ruby
  gem:
    name: bundler
    state: present
    user_install: no